spring:
  profiles:
    active:
    - dev #当前使用的环境
---
content: dev content 刷新坏了
server:
  port: 6001
spring:
  profiles: dev #开发环境
  application:
    name: config-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka01.com:1001/eureka/
---
content: test content
server:
  port: 6002
spring:
  profiles: test #测试环境
  application:
    name: config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka01.com:1001/eureka/
